-- 1. PROFILES TABLE
-- Stores public-facing profile data for each user.
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  username TEXT UNIQUE,
  role TEXT DEFAULT 'user',
  email TEXT,
  must_change_password BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (id),
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- 2. LOGS TABLE
-- Stores a record of administrative actions.
CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  username TEXT,
  action TEXT NOT NULL,
  details JSONB
);

-- 3. RLS (ROW LEVEL SECURITY) SETUP

-- Enable RLS for all relevant tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Public access for reading" ON public.events;
DROP POLICY IF EXISTS "Public read access for events" ON public.events;
DROP POLICY IF EXISTS "Admin full access" ON public.events;
DROP POLICY IF EXISTS "Admin full access for events" ON public.events;

DROP POLICY IF EXISTS "Public access for reading" ON public.tags;
DROP POLICY IF EXISTS "Public read access for tags" ON public.tags;
DROP POLICY IF EXISTS "Admin full access" ON public.tags;
DROP POLICY IF EXISTS "Admin full access for tags" ON public.tags;

DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;

DROP POLICY IF EXISTS "Admins can view logs" ON public.logs;
DROP POLICY IF EXISTS "Admins can insert logs" ON public.logs;

-- PROFILES POLICIES
-- Users can see their own profile.
CREATE POLICY "Users can view their own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);
-- Users can update their own profile.
CREATE POLICY "Users can update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- EVENTS POLICIES
-- Anyone can read events (for the public site).
CREATE POLICY "Public read access for events" ON public.events
  FOR SELECT USING (true);
-- Only users with the 'admin' role can create, update, or delete events.
CREATE POLICY "Admin full access for events" ON public.events
  FOR ALL USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

-- TAGS POLICIES
-- Anyone can read tags.
CREATE POLICY "Public read access for tags" ON public.tags
  FOR SELECT USING (true);
-- Only users with the 'admin' role can manage tags.
CREATE POLICY "Admin full access for tags" ON public.tags
  FOR ALL USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

-- LOGS POLICIES
-- Only admins can view logs.
CREATE POLICY "Admins can view logs" ON public.logs
  FOR SELECT USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );
-- Only admins can insert logs (though this will be done via functions/triggers for safety).
CREATE POLICY "Admins can insert logs" ON public.logs
  FOR INSERT WITH CHECK (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

-- 4. HELPER FUNCTION & TRIGGER
-- This function automatically creates a profile entry when a new user signs up.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username, role)
  VALUES (
    new.id,
    new.email,
    -- Generate a default username from the email prefix, ensuring it's unique
    -- Example: 'test@example.com' -> 'test' or 'test1', 'test2', etc.
    (SELECT split_part(new.email, '@', 1) || COALESCE(
      (SELECT '.' || (COUNT(*) + 1)::TEXT FROM public.profiles WHERE username LIKE (split_part(new.email, '@', 1) || '%')),
      ''
    )),
    'user' -- Default role is 'user'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- This trigger calls the function after a new user is created in the auth system.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. FUNCTION TO GET USERNAME
-- A helper to get a username from a user ID.
CREATE OR REPLACE FUNCTION public.get_username_from_id(user_id uuid)
RETURNS TEXT AS $$
DECLARE
  uname TEXT;
BEGIN
  SELECT username INTO uname FROM public.profiles WHERE id = user_id;
  RETURN uname;
END;
$$ LANGUAGE plpgsql;


-- 6. SEED ADMIN USER
-- This statement will find the user with the specified email and grant them the 'admin' role.
-- IMPORTANT: Make sure the user already exists in Supabase Auth before running this.
-- If you just signed up, this will work.
UPDATE public.profiles
SET
  role = 'admin',
  username = 'admin',
  must_change_password = FALSE
WHERE email = 'bottaridennis@gmail.com';

-- If for some reason the profile was not created automatically, this will create it.
-- Run this part ONLY if the UPDATE above affects 0 rows.
INSERT INTO public.profiles (id, email, username, role, must_change_password)
SELECT
  id,
  'bottaridennis@gmail.com',
  'admin',
  'admin',
  FALSE
FROM auth.users
WHERE email = 'bottaridennis@gmail.com'
ON CONFLICT (id) DO UPDATE SET must_change_password = FALSE;

-- 7. FUNCTION TO GET EMAIL FROM USERNAME (for login)
CREATE OR REPLACE FUNCTION public.get_email_from_username(p_username TEXT)
RETURNS TEXT AS $$
DECLARE
  user_email TEXT;
BEGIN
  SELECT email INTO user_email
  FROM public.profiles
  WHERE username = p_username;
  
  RETURN user_email;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
